eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka:8761/eureka} // this line commented due to in local i was not able to run ss Cloud gateway
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


# spring:
#   datasource:
#     url: jdbc:postgresql://52.66.98.25:5433/global_uat
#     username: ubuntu
#     password: ubuntu@deepmindz2023
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update # or create, create-drop, none
#     show-sql: true # Set to true to show SQL queries in the console
    
